Fix casing issues for System.configuration and System.XML
jnm2/ReferenceAssemblies.net35 pull request #2
Opened 2020-01-16 14:29 UTC by thinkbeforecoding

This is a minor change to fix System.configuration and System.XML casing to System.Configuration and System.XML.

This odd casing is present in older versions of dotnet framework and cause probleme when trying to build net35 projects using this nuget on linux. dotnet on Linux cannot resolve assemblies when the dll casing is not consistent with the assembly name.

2020-01-16 14:32 UTC, thinkbeforecoding commented
This is a fix for #3

2020-01-16 14:33 UTC, thinkbeforecoding commented
It is solved here by reading assembly name to get the appropriate dll casing.

2020-01-16 20:01 UTC, jnm2 requested changes
Thanks so much for reporting and fixing this!

2020-01-16 20:01 UTC, jnm2 commented on src/jnm2.ReferenceAssemblies.net35.nuspec
> +    <version>1.0.1-preview</version>
I don't want to decide whether to use `1.0.1-preview.1` or `1.0.1` right now, so could you exclude this change please?

2020-01-16 20:01 UTC, jnm2 commented on build/Program.cs
> +            .Select(path => path));
Can you help me understand why this change was made?

2020-01-16 20:01 UTC, jnm2 commented on build/Program.cs
> +                    if (Path.GetExtension(filePath) == ".xml")
Please use `HasAnyExtension` for consistency with the surrounding code and because the comparison should be made case-insensitively.

2020-01-16 20:01 UTC, jnm2 commented on build/Program.cs
> +                        var asm = System.Reflection.Assembly.ReflectionOnlyLoadFrom(filePath);
Could you use `AssemblyName.GetAssemblyName(filePath)` instead of loading the assembly?

2020-01-16 20:02 UTC, jnm2 commented
> This is a fix for #3

ℹ I edited your first comment to follow https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords.

2020-01-16 20:29 UTC, thinkbeforecoding commented on build/Program.cs
> +            .Select(path => path));
Oups.. that I revert this one... even if I had no prb with it

2020-01-16 20:35 UTC, thinkbeforecoding commented on build/Program.cs
> +                        var asm = System.Reflection.Assembly.ReflectionOnlyLoadFrom(filePath);
Changed !

2020-01-16 20:37 UTC, jnm2 commented
@thinkbeforecoding You don't need to do anything but just letting you know: When I merge this, I'm going to use the squash option because of the 'revert'/'remove' commits so that the line history is clean. (If you would rather I don't squash everything, I'd ask you to squash the 'revert'/'remove' commits yourself and force push. I'd also be happy to walk you through that.)

2020-01-16 20:43 UTC, jnm2 commented
I'm going to set up Linux tests (#4) or verify this manually myself before publishing another NuGet package.

2020-01-16 21:36 UTC, thinkbeforecoding commented
Yes, I detected the problem with System.configuration and System.XML
because I used them, but there may be others. The implemented solution
should fix it.

That said, I'm not even sure it has been fixed in official MS packages...

Le jeu. 16 janv. 2020 à 21:43, Joseph Musser <notifications@github.com> a
écrit :

> I'm going to set up Linux tests (#4
> <https://github.com/jnm2/ReferenceAssemblies.net35/issues/4>) or verify
> this manually myself before publishing another NuGet package.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jnm2/ReferenceAssemblies.net35/pull/2?email_source=notifications&email_token=AABD2HLO324S3VGTMFNKI5TQ6DBF3A5CNFSM4KHU5MFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJFPICI#issuecomment-575337481>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABD2HPCQENYPPRH6N4JNOTQ6DBF3ANCNFSM4KHU5MFA>
> .
>

2020-01-16 21:46 UTC, jnm2 approved these changes

2020-01-16 21:53 UTC, thinkbeforecoding commented
I squashed everything. It's far cleaner now

2020-01-16 22:18 UTC, merged

2020-01-16 22:18 UTC, jnm2 commented
I appreciate this!

2020-01-17 07:43 UTC, thinkbeforecoding commented
Thank you very much for all this !